# -*- coding: utf-8 -*-
"""Model trainig using Linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-drSuywTLOFKs9A_kZu69DMRjZAEFR8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Advertising.csv")

df.shape

df.head()

df.info()

df.tail()

df.isnull().sum()

df.isna()

sns.histplot(x=df['TV'],kde=True,bins=30)

sns.histplot(x=df['Newspaper'],kde=True,bins=30)

sns.histplot(x=df['Radio'],kde=True,bins=30)

sns.histplot(x=df['Unnamed: 0'],kde=True,bins=30)

sns.histplot(x=df['Sales'],kde=True,bins=40)

df['Newspaper'].skew()

"""it is a non normal range of distribution and it is left skewed , which is in the range more than the normal distribution range i.e -0.5 to 0.5"""

df['Radio'].skew()

"""    it is in the normal range distribution
    where it lies between the normal range i.e -0.5 to 0.5
    we can consider it as a normal range

"""

df['Sales'].skew()

"""    it is in the normal range distribution
    where it lies between the normal range i.e -0.5 to 0.5
    we can consider it as a normal range



"""

df['TV'].skew()

"""it is in the normal range



"""

df['Unnamed: 0'].skew()

"""it is in the normal range



"""

np.mean(df['Sales'])

df.columns

sns.scatterplot(x=df['Newspaper'],y=df['Sales'])

""" Random and  Negative"""

sns.scatterplot(x=df['TV'],y=df['Sales'])

"""Positive relationship"""

sns.scatterplot(x=df['Radio'],y=df['Sales'])

"""Positive"""

sns.scatterplot(x=df['Unnamed: 0'],y=df['Sales'])

"""Random"""

df.corr()

"""    Variable	Correlation with Sales	Insight
    TV	0.782	Strong positive relation
    Radio	0.576	Moderate positive relation
    Newspaper	0.228	Weak positive relation
    Unnamed: 0	-0.051	weak Negative i.e no relation
"""

sns.heatmap(df.corr(),annot=True,cmap='Blues')

df.drop('Unnamed: 0',axis=1,inplace=True)

df.columns

sns.heatmap(df.corr(),annot=True,cmap='Blues')

x=df[['TV']]

y=df.Sales

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

print(len(x_test))
print(len(x_train))

"""    Creating a model"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)
y_predict=LR.predict(x_test)

print(y_predict)

from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error
r2_score(y_test,y_predict)

mean_squared_error(y_test,y_predict)

mean_absolute_error(y_test,y_predict)

root_mean_squared_error(y_test,y_predict)

X=df[['Radio']]

Y=df.Sales

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)
y_predict=LR.predict(x_test)

from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error
r2_score(y_test,y_predict)

mean_squared_error(y_test,y_predict)

mean_absolute_error(y_test,y_predict)

root_mean_squared_error(y_test,y_predict)

X=df[['Newspaper']]
Y=df.Sales

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)
y_predict=LR.predict(x_test)

from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error
r2_score(y_test,y_predict)

mean_squared_error(y_test,y_predict)

mean_absolute_error(y_test,y_predict)

root_mean_squared_error(y_test,y_predict)

X=df[['TV','Radio','Newspaper']]
Y=df.Sales

X

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)
y_predict=LR.predict(x_test)

from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error
r2_score(y_test,y_predict)

print(mean_squared_error(y_test,y_predict))
print(mean_absolute_error(y_test,y_predict))
print(root_mean_squared_error(y_test,y_predict))

